### ISSUE TITLE
希望CONTRIBUTOS中能剔除机器人的统计数据

### ISSUE THREAD

**Issue by hu-qi** [kaiyuanshe/Open-source-training-camp#11]
# 进击的机器人

![image](https://user-images.githubusercontent.com/17986122/93296130-28c79880-f821-11ea-809b-6e8536f9490f.png)

如图所示，机器人已经超过了人类，至少比人勤奋[/滑稽]。希望新版本中能有配置能剔除机器人的贡献统计。

**Comment by hu-qi** [comment]
add label again

**Comment by frank-zsy** [comment]
这个项目没有安装机器人，所以没有自动 label 的功能哈，另外如果要打的话，应该是 Refactor 类型，因为是一个小的特性修改，而不是一个 bug

**Comment by hu-qi** [comment]
感谢！最最开始打的是[help-wanted]，以为不对看之前[bug]有效就试了试，然后发现应该是没有加issues相关的配置。学到了，看来github中还有好多通识需要学习。



---原始邮件---
发件人: "Frank Zhao"<notifications@github.com&gt;
发送时间: 2020年9月16日(周三) 下午3:32
收件人: "kaiyuanshe/Open-source-training-camp"<Open-source-training-camp@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"huqi"<820965339@qq.com&gt;;
主题: Re: [kaiyuanshe/Open-source-training-camp] 希望CONTRIBUTOS中能剔除机器人的统计数据 (#11)




 
这个项目没有安装机器人，所以没有自动 label 的功能哈，另外如果要打的话，应该是 Refactor 类型，因为是一个小的特性修改，而不是一个 bug

**Comment by frank-zsy** [comment]
@hu-qi 已剔除当前机器人账号，请关注今天的提交情况
