### ISSUE TITLE
ISSUE_TEMPLATE如果是文件夹的形式，里面的文件该怎么命名？

### ISSUE THREAD

**Issue by hu-qi** [kaiyuanshe/Open-source-training-camp#18]
请问下老师，文件夹的形式时，怎么命名？是对应label吗？

**Comment by frank-zsy** [comment]
https://docs.github.com/cn/github/building-a-strong-community/configuring-issue-templates-for-your-repository 可以参考一下这个文档，里面有非常详细的流程介绍。
