### ISSUE TITLE
关于评定标准的一些疑问

### ISSUE THREAD

**Issue by vcjmhg** [kaiyuanshe/Open-source-training-camp#21]
老师您好！在您制定的规范中，更多的是针对一个完全新的项目的评定，但是有的同学可能会参加一些比较成熟的开源项目，针对这样的同学请问如何参与评定那？

**Comment by frank-zsy** [comment]
如果是参与已有的项目，我们也按照活跃度来统计和评定，你可以在 Projects 文件中添加项目和成员信息，不需要添加后面两段内容，标注一下是参与非原创项目即可。后续我们会有工具来统计没有机器人的项目中的活跃度情况。

**Comment by vcjmhg** [comment]
明白了，谢谢！
