### ISSUE TITLE
学长好。请教一下学长

### ISSUE THREAD

**Issue by YuRui997** [kaiyuanshe/Open-source-training-camp#27]
学长好，因为我们小组昨天才创建了项目，还没有添加到特训营项目列表里。我把特训营的项目clone到了我的本地电脑上，我该对projects.md文件做哪些更改之后才可以提出PR呢？

**Comment by frank-zsy** [comment]
你需要首先了解一下完整的 PR 流程，可以参考张齐勋老师的 PR 相关流程的公众号文章。你需要将项目 Fork 到你的账号，然后再 Clone 到本地，然后在 Projects.md 中按照其他项目的格式，添加项目名称、成员信息、文件状态检查、项目数据统计等几部分内容，然后提 PR 上来。

需要注意的是如果你们是多人项目，提交的项目应该是大家协作的那一个主项目。
