### ISSUE TITLE
学长好，为什么今晚机器人没有对我的仓库自动提交pr呢？

### ISSUE THREAD

**Issue by bigbeats** [kaiyuanshe/Open-source-training-camp#32]
学长晚上好，今晚我组的项目在22:00时没有收到机器人自动提交的Pr，昨天是有正常收到Pr的。
项目地址：https://github.com/opensource-team/Git-Github-notes-for-study
相比昨日，今天的修改如下：
1.update了一个已有的md文件；
2.创建了两个Issues；
3.创建了一个文件夹，并在文件夹中放入了一张图片；
4.创建了一个新的md文件。

**Comment by frank-zsy** [comment]
是不是已经移除或限制了机器人权限，请检查一下机器人是否正确安装，我这边从日志来看，似乎目前该项目并没有安装机器人。

**Comment by bigbeats** [comment]
谢谢老师解答！
我刚才去项目里看了。仓库安了机器人，并且给机器人的权限都是放开的。
以下是项目中机器人状态的截图，还请学长白天有空时看一下：
https://github.com/bigbeats/Git-Github-notes-for-study/blob/master/images-folder/robotStatus.png.png
学长，以下是两点附加说明：
1.该截图的存放仓库是原项目的fork仓库，并非原仓库。
2.该截图可能由于过大，不能在网页上完整显示，下载后可以完整显示。

**Comment by frank-zsy** [comment]
经查这是一个 Hypertrons 的 Bug，由于安装机器人的仓库过多，导致我启动时未能获取到完整的安装列表，已修复，多谢反馈~

**Comment by bigbeats** [comment]
明白了！感谢老师检查！

**Comment by frank-zsy** [comment]
已确认修复 https://github.com/opensource-team/Git-Github-notes-for-study/pull/32
