### ISSUE TITLE
学长好，请问Fork的仓库如何保持与原仓库同步

### ISSUE THREAD

**Issue by UtenaTenjo371** [kaiyuanshe/Open-source-training-camp#44]
我之前查询的方法是在bash中添加原仓库，将原仓库fetch到暂存区，merge到master，再push给自己的仓库，有没有跳过本地工作区，直接在github上操作的方法呢

**Comment by frank-zsy** [comment]
目前同步上游仓库基本只能通过本地来操作的，Web 页面也是可以的，但流程较为麻烦。

需要你在 fork 的仓库新建一个 PR，并选择从上游 master 分支向 fork 仓库 master 分支提起 PR，解决冲突后合并就完成了一次同步。
