### ISSUE TITLE
请教一下学长关于CONTRIBUTORS的问题

### ISSUE THREAD

**Issue by XieLingfan** [kaiyuanshe/Open-source-training-camp#46]
作为组长，我贡献了很多，每天都有新的提交。但我的贡献值很低，而且最近都没有增加过
![微信图片_20200924111503](https://user-images.githubusercontent.com/39857428/94096802-9a25cd80-fe57-11ea-8a18-ec6be80b524c.png)

是否因为是自己的仓库，没有PR，导致贡献不增加？

**Comment by frank-zsy** [comment]
是的，活跃度的计算不会计入直接 push 的贡献，只有 Issue、PR 的贡献会计入。

如果你的仓库有多人协作，你直接 push commit 是非常不合适的，会导致其他人出现冲突，而且跳过了 review 的过程，这种项目不能算是标准的开源项目。

**Comment by XieLingfan** [comment]
好的，谢谢学长
