### ISSUE TITLE
机器让人安装成功没有收到PR报告

### ISSUE THREAD

**Issue by Kenscofield** [kaiyuanshe/Open-source-training-camp#55]
学长好，机器人安装成功了，master分支下.github文件里存在文件hypertrons.json，但是并没有收到每日PR报告，请问这是什么原因？

**Comment by wenmingyuan** [comment]
我们组有同样问题，在6天前安装的机器人，但机器人只提交过一次PR。项目地址：'https://github.com/TTa77/OSTC-SS2020-2ndBachelors'，我们的项目还没有添加到'Projects.md'。

**Comment by frank-zsy** [comment]
> 学长好，机器人安装成功了，master分支下.github文件里存在文件hypertrons.json，但是并没有收到每日PR报告，请问这是什么原因？

请问具体是哪个项目？

**Comment by frank-zsy** [comment]
> 我们组有同样问题，在6天前安装的机器人，但机器人只提交过一次PR。项目地址：'[https://github.com/TTa77/OSTC-SS2020-2ndBachelors'，我们的项目还没有添加到'Projects.md'。](https://github.com/TTa77/OSTC-SS2020-2ndBachelors'%EF%BC%8C%E6%88%91%E4%BB%AC%E7%9A%84%E9%A1%B9%E7%9B%AE%E8%BF%98%E6%B2%A1%E6%9C%89%E6%B7%BB%E5%8A%A0%E5%88%B0'Projects.md'%E3%80%82)

我看了一下你们的项目，在 6 天前安装机器人后一直没有过其他的活跃活动，Issue 和 PR 的活跃都在 6 天之前，这会导致活跃度不会发生变化，如果活跃度不发生变化，则机器人不会重新提起 PR，因为 CONTRIBUTORS 文件内容是不变的。

这个组件是每天都会运行的，但不表示会每天提 PR，只有内容发生变化时才会提 PR。

**Comment by Kenscofield** [comment]
项目地址https://github.com/Kenscofield/HUILV，大概原因和上面一样吧，谢谢学长

**Comment by Kenscofield** [comment]
> > 学长好，机器人安装成功了，master分支下.github文件里存在文件hypertrons.json，但是并没有收到每日PR报告，请问这是什么原因？
> 
> 请问具体是哪个项目？

项目地址https://github.com/Kenscofield/HUILV，大概原因和上面一样吧，谢谢学长

**Comment by frank-zsy** [comment]
> > > 学长好，机器人安装成功了，master分支下.github文件里存在文件hypertrons.json，但是并没有收到每日PR报告，请问这是什么原因？
> > 
> > 
> > 请问具体是哪个项目？
> 
> 项目地址[https://github.com/Kenscofield/HUILV，大概原因和上面一样吧，谢谢学长](https://github.com/Kenscofield/HUILV%EF%BC%8C%E5%A4%A7%E6%A6%82%E5%8E%9F%E5%9B%A0%E5%92%8C%E4%B8%8A%E9%9D%A2%E4%B8%80%E6%A0%B7%E5%90%A7%EF%BC%8C%E8%B0%A2%E8%B0%A2%E5%AD%A6%E9%95%BF)

嗯，我看到你的上游仓库是每天都有 PR 的，下游仓库就不要安装机器人了

**Comment by Kenscofield** [comment]
> > > > 学长好，机器人安装成功了，master分支下.github文件里存在文件hypertrons.json，但是并没有收到每日PR报告，请问这是什么原因？
> > > 
> > > 
> > > 请问具体是哪个项目？
> > 
> > 
> > 项目地址[https://github.com/Kenscofield/HUILV，大概原因和上面一样吧，谢谢学长](https://github.com/Kenscofield/HUILV%EF%BC%8C%E5%A4%A7%E6%A6%82%E5%8E%9F%E5%9B%A0%E5%92%8C%E4%B8%8A%E9%9D%A2%E4%B8%80%E6%A0%B7%E5%90%A7%EF%BC%8C%E8%B0%A2%E8%B0%A2%E5%AD%A6%E9%95%BF)
> 
> 嗯，我看到你的上游仓库是每天都有 PR 的，下游仓库就不要安装机器人了

好的好的，谢谢学长

**Comment by wenmingyuan** [comment]
> 
> 
> > 我们组有同样问题，在6天前安装的机器人，但机器人只提交过一次PR。项目地址：'[https://github.com/TTa77/OSTC-SS2020-2ndBachelors'，我们的项目还没有添加到'Projects.md'。](https://github.com/TTa77/OSTC-SS2020-2ndBachelors'%EF%BC%8C%E6%88%91%E4%BB%AC%E7%9A%84%E9%A1%B9%E7%9B%AE%E8%BF%98%E6%B2%A1%E6%9C%89%E6%B7%BB%E5%8A%A0%E5%88%B0'Projects.md'%E3%80%82)
> 
> 我看了一下你们的项目，在 6 天前安装机器人后一直没有过其他的活跃活动，Issue 和 PR 的活跃都在 6 天之前，这会导致活跃度不会发生变化，如果活跃度不发生变化，则机器人不会重新提起 PR，因为 CONTRIBUTORS 文件内容是不变的。
> 
> 这个组件是每天都会运行的，但不表示会每天提 PR，只有内容发生变化时才会提 PR。

明白了，谢谢学长。
